/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthSignupRouteImport } from './routes/_auth/signup'
import { Route as DashboardCompaniesRouteImport } from './routes/_dashboard/companies'
import { Route as DashboardContactsRouteImport } from './routes/_dashboard/contacts'
import { Route as DashboardDashboardRouteImport } from './routes/_dashboard/dashboard'
import { Route as DashboardDealsRouteImport } from './routes/_dashboard/deals'
import { Route as OnboardingOnboardingRouteImport } from './routes/_onboarding/onboarding'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const DashboardCompaniesRoute = DashboardCompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardContactsRoute = DashboardContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDashboardRoute = DashboardDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDealsRoute = DashboardDealsRouteImport.update({
  id: '/deals',
  path: '/deals',
  getParentRoute: () => DashboardRoute,
} as any)
const OnboardingOnboardingRoute = OnboardingOnboardingRouteImport.update({
  id: '/_onboarding/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mcp': typeof McpRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/companies': typeof DashboardCompaniesRoute
  '/contacts': typeof DashboardContactsRoute
  '/dashboard': typeof DashboardDashboardRoute
  '/deals': typeof DashboardDealsRoute
  '/onboarding': typeof OnboardingOnboardingRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mcp': typeof McpRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/companies': typeof DashboardCompaniesRoute
  '/contacts': typeof DashboardContactsRoute
  '/dashboard': typeof DashboardDashboardRoute
  '/deals': typeof DashboardDealsRoute
  '/onboarding': typeof OnboardingOnboardingRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_dashboard': typeof DashboardRouteWithChildren
  '/mcp': typeof McpRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/_dashboard/companies': typeof DashboardCompaniesRoute
  '/_dashboard/contacts': typeof DashboardContactsRoute
  '/_dashboard/dashboard': typeof DashboardDashboardRoute
  '/_dashboard/deals': typeof DashboardDealsRoute
  '/_onboarding/onboarding': typeof OnboardingOnboardingRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/mcp'
    | '/login'
    | '/signup'
    | '/companies'
    | '/contacts'
    | '/dashboard'
    | '/deals'
    | '/onboarding'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/mcp'
    | '/login'
    | '/signup'
    | '/companies'
    | '/contacts'
    | '/dashboard'
    | '/deals'
    | '/onboarding'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_dashboard'
    | '/mcp'
    | '/_auth/login'
    | '/_auth/signup'
    | '/_dashboard/companies'
    | '/_dashboard/contacts'
    | '/_dashboard/dashboard'
    | '/_dashboard/deals'
    | '/_onboarding/onboarding'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  McpRoute: typeof McpRoute
  OnboardingOnboardingRoute: typeof OnboardingOnboardingRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_dashboard/companies': {
      id: '/_dashboard/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof DashboardCompaniesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/contacts': {
      id: '/_dashboard/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof DashboardContactsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/dashboard': {
      id: '/_dashboard/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardDashboardRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/deals': {
      id: '/_dashboard/deals'
      path: '/deals'
      fullPath: '/deals'
      preLoaderRoute: typeof DashboardDealsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_onboarding/onboarding': {
      id: '/_onboarding/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface DashboardRouteChildren {
  DashboardCompaniesRoute: typeof DashboardCompaniesRoute
  DashboardContactsRoute: typeof DashboardContactsRoute
  DashboardDashboardRoute: typeof DashboardDashboardRoute
  DashboardDealsRoute: typeof DashboardDealsRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardCompaniesRoute: DashboardCompaniesRoute,
  DashboardContactsRoute: DashboardContactsRoute,
  DashboardDashboardRoute: DashboardDashboardRoute,
  DashboardDealsRoute: DashboardDealsRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  McpRoute: McpRoute,
  OnboardingOnboardingRoute: OnboardingOnboardingRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
