/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthSignupRouteImport } from './routes/_auth/signup'
import { Route as DashboardCompaniesRouteImport } from './routes/_dashboard/companies'
import { Route as DashboardContactsRouteImport } from './routes/_dashboard/contacts'
import { Route as DashboardDashboardRouteImport } from './routes/_dashboard/dashboard'
import { Route as DashboardDealsRouteImport } from './routes/_dashboard/deals'
import { Route as DashboardSettingsRouteImport } from './routes/_dashboard/settings'
import { Route as OnboardingOnboardingRouteImport } from './routes/_onboarding/onboarding'
import { Route as DashboardSettingsIndexRouteImport } from './routes/_dashboard/settings/index'
import { Route as DashboardSettingsConnectionsRouteImport } from './routes/_dashboard/settings/connections'
import { Route as DashboardSettingsMandateRouteImport } from './routes/_dashboard/settings/mandate'
import { Route as DashboardSettingsMembersRouteImport } from './routes/_dashboard/settings/members'
import { Route as DashboardSettingsSsoRouteImport } from './routes/_dashboard/settings/sso'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const DashboardCompaniesRoute = DashboardCompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardContactsRoute = DashboardContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDashboardRoute = DashboardDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDealsRoute = DashboardDealsRouteImport.update({
  id: '/deals',
  path: '/deals',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const OnboardingOnboardingRoute = OnboardingOnboardingRouteImport.update({
  id: '/_onboarding/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsIndexRoute = DashboardSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardSettingsRoute,
} as any)
const DashboardSettingsConnectionsRoute =
  DashboardSettingsConnectionsRouteImport.update({
    id: '/connections',
    path: '/connections',
    getParentRoute: () => DashboardSettingsRoute,
  } as any)
const DashboardSettingsMandateRoute =
  DashboardSettingsMandateRouteImport.update({
    id: '/mandate',
    path: '/mandate',
    getParentRoute: () => DashboardSettingsRoute,
  } as any)
const DashboardSettingsMembersRoute =
  DashboardSettingsMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => DashboardSettingsRoute,
  } as any)
const DashboardSettingsSsoRoute = DashboardSettingsSsoRouteImport.update({
  id: '/sso',
  path: '/sso',
  getParentRoute: () => DashboardSettingsRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mcp': typeof McpRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/companies': typeof DashboardCompaniesRoute
  '/contacts': typeof DashboardContactsRoute
  '/dashboard': typeof DashboardDashboardRoute
  '/deals': typeof DashboardDealsRoute
  '/settings': typeof DashboardSettingsRouteWithChildren
  '/onboarding': typeof OnboardingOnboardingRoute
  '/settings/connections': typeof DashboardSettingsConnectionsRoute
  '/settings/mandate': typeof DashboardSettingsMandateRoute
  '/settings/members': typeof DashboardSettingsMembersRoute
  '/settings/sso': typeof DashboardSettingsSsoRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/settings/': typeof DashboardSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mcp': typeof McpRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/companies': typeof DashboardCompaniesRoute
  '/contacts': typeof DashboardContactsRoute
  '/dashboard': typeof DashboardDashboardRoute
  '/deals': typeof DashboardDealsRoute
  '/onboarding': typeof OnboardingOnboardingRoute
  '/settings/connections': typeof DashboardSettingsConnectionsRoute
  '/settings/mandate': typeof DashboardSettingsMandateRoute
  '/settings/members': typeof DashboardSettingsMembersRoute
  '/settings/sso': typeof DashboardSettingsSsoRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/settings': typeof DashboardSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_dashboard': typeof DashboardRouteWithChildren
  '/mcp': typeof McpRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/_dashboard/companies': typeof DashboardCompaniesRoute
  '/_dashboard/contacts': typeof DashboardContactsRoute
  '/_dashboard/dashboard': typeof DashboardDashboardRoute
  '/_dashboard/deals': typeof DashboardDealsRoute
  '/_dashboard/settings': typeof DashboardSettingsRouteWithChildren
  '/_onboarding/onboarding': typeof OnboardingOnboardingRoute
  '/_dashboard/settings/connections': typeof DashboardSettingsConnectionsRoute
  '/_dashboard/settings/mandate': typeof DashboardSettingsMandateRoute
  '/_dashboard/settings/members': typeof DashboardSettingsMembersRoute
  '/_dashboard/settings/sso': typeof DashboardSettingsSsoRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_dashboard/settings/': typeof DashboardSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/mcp'
    | '/login'
    | '/signup'
    | '/companies'
    | '/contacts'
    | '/dashboard'
    | '/deals'
    | '/settings'
    | '/onboarding'
    | '/settings/connections'
    | '/settings/mandate'
    | '/settings/members'
    | '/settings/sso'
    | '/api/auth/$'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/mcp'
    | '/login'
    | '/signup'
    | '/companies'
    | '/contacts'
    | '/dashboard'
    | '/deals'
    | '/onboarding'
    | '/settings/connections'
    | '/settings/mandate'
    | '/settings/members'
    | '/settings/sso'
    | '/api/auth/$'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_dashboard'
    | '/mcp'
    | '/_auth/login'
    | '/_auth/signup'
    | '/_dashboard/companies'
    | '/_dashboard/contacts'
    | '/_dashboard/dashboard'
    | '/_dashboard/deals'
    | '/_dashboard/settings'
    | '/_onboarding/onboarding'
    | '/_dashboard/settings/connections'
    | '/_dashboard/settings/mandate'
    | '/_dashboard/settings/members'
    | '/_dashboard/settings/sso'
    | '/api/auth/$'
    | '/_dashboard/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  McpRoute: typeof McpRoute
  OnboardingOnboardingRoute: typeof OnboardingOnboardingRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_dashboard/companies': {
      id: '/_dashboard/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof DashboardCompaniesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/contacts': {
      id: '/_dashboard/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof DashboardContactsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/dashboard': {
      id: '/_dashboard/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardDashboardRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/deals': {
      id: '/_dashboard/deals'
      path: '/deals'
      fullPath: '/deals'
      preLoaderRoute: typeof DashboardDealsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/settings': {
      id: '/_dashboard/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_onboarding/onboarding': {
      id: '/_onboarding/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/settings/': {
      id: '/_dashboard/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof DashboardSettingsIndexRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
    '/_dashboard/settings/connections': {
      id: '/_dashboard/settings/connections'
      path: '/connections'
      fullPath: '/settings/connections'
      preLoaderRoute: typeof DashboardSettingsConnectionsRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
    '/_dashboard/settings/mandate': {
      id: '/_dashboard/settings/mandate'
      path: '/mandate'
      fullPath: '/settings/mandate'
      preLoaderRoute: typeof DashboardSettingsMandateRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
    '/_dashboard/settings/members': {
      id: '/_dashboard/settings/members'
      path: '/members'
      fullPath: '/settings/members'
      preLoaderRoute: typeof DashboardSettingsMembersRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
    '/_dashboard/settings/sso': {
      id: '/_dashboard/settings/sso'
      path: '/sso'
      fullPath: '/settings/sso'
      preLoaderRoute: typeof DashboardSettingsSsoRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface DashboardSettingsRouteChildren {
  DashboardSettingsConnectionsRoute: typeof DashboardSettingsConnectionsRoute
  DashboardSettingsMandateRoute: typeof DashboardSettingsMandateRoute
  DashboardSettingsMembersRoute: typeof DashboardSettingsMembersRoute
  DashboardSettingsSsoRoute: typeof DashboardSettingsSsoRoute
  DashboardSettingsIndexRoute: typeof DashboardSettingsIndexRoute
}

const DashboardSettingsRouteChildren: DashboardSettingsRouteChildren = {
  DashboardSettingsConnectionsRoute: DashboardSettingsConnectionsRoute,
  DashboardSettingsMandateRoute: DashboardSettingsMandateRoute,
  DashboardSettingsMembersRoute: DashboardSettingsMembersRoute,
  DashboardSettingsSsoRoute: DashboardSettingsSsoRoute,
  DashboardSettingsIndexRoute: DashboardSettingsIndexRoute,
}

const DashboardSettingsRouteWithChildren =
  DashboardSettingsRoute._addFileChildren(DashboardSettingsRouteChildren)

interface DashboardRouteChildren {
  DashboardCompaniesRoute: typeof DashboardCompaniesRoute
  DashboardContactsRoute: typeof DashboardContactsRoute
  DashboardDashboardRoute: typeof DashboardDashboardRoute
  DashboardDealsRoute: typeof DashboardDealsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRouteWithChildren
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardCompaniesRoute: DashboardCompaniesRoute,
  DashboardContactsRoute: DashboardContactsRoute,
  DashboardDashboardRoute: DashboardDashboardRoute,
  DashboardDealsRoute: DashboardDealsRoute,
  DashboardSettingsRoute: DashboardSettingsRouteWithChildren,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  McpRoute: McpRoute,
  OnboardingOnboardingRoute: OnboardingOnboardingRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
