export {
  authClient,
  getSession,
  signIn,
  signOut,
  signUp,
  useSession,
  requestPasswordReset,
  resetPassword,
  verifyEmail,
  sendVerificationEmail,
  changePassword,
  changeEmail,
  updateUser,
  listAccounts,
  unlinkAccount,
  revokeSession,
  revokeOtherSessions,
} from '@repo/auth/client'
